### PR TITLE
Fix errors when using with Vue 3

### LINKED ISSUE #217: Vue 3 Support
With Vue3 on the horizon, this library should probably support it. I've gotten started with Vue 3 in one of my projects, so I'll try and fork this and open a PR when I have time.

- `vue@3.0.0-rc.5`
- `vue-recaptcha-v3@1.9.0`

### Typescript

Looks like this library is missing an `install` method?

```ts
import { VueReCaptcha } from 'vue-recaptcha-v3';

createApp(App)
  .use(VueReCaptcha, { siteKey: '<token>' })
  .mount('#app');
```

```
Argument of type '(Vue: typeof import("<project>/node_modules/vue/dist/vue"), options: IReCaptchaOptions) => void' is not assignable to parameter of type 'Plugin_2'.
  Type '(Vue: typeof import("<project>/node_modules/vue/dist/vue"), options: IReCaptchaOptions) => void' is not assignable to type 'PluginInstallFunction & { install?: PluginInstallFunction | undefined; }'.
    Type '(Vue: typeof import("<project>/node_modules/vue/dist/vue"), options: IReCaptchaOptions) => void' is not assignable to type 'PluginInstallFunction'.
      Types of parameters 'Vue' and 'app' are incompatible.
        Type 'App<any>' is missing the following properties from type 'typeof import("node_modules/vue/dist/vue")': compile, useCssModule, useCssVars, createApp, and 104 more.
```

### Usage

If you ignore the TS error and continue on, you get an error at runtime because there is no longer a default export from `vue`:

```
Uncaught TypeError: Vue.prototype is undefined
    > VueReCaptcha ReCaptchaVuePlugin.js:46
```

### PR DESCRIPTION
**Pull request by aklinker1**
#### Summary

This closes #217 

- Updated plugin structure to use install method to fix TS error mentioned in the issue
- Added composition helper function, `useReCaptcha`
- Upgraded to `vue@^3.0.0-rc.5`

#### Resources

- https://github.com/vuejs/vuex/blob/4.0/src/store.js
- https://github.com/vuejs/vue-router-next/blob/910634e659be83eabf65b2215e201cdea1c02761/src/router.ts
- https://learnvue.co/2020/03/designing-vue3-plugins-using-provide-and-inject/
- https://vuejs.org/v2/guide/plugins.html

#### Other Comments

- First time writing a plugin, so I might have over-restructured the main file
- `README.md` might have some lint errors in new example code, your code style is different than mine but I tried to match it, so let me know if I missed anything
- Couldn't get the demo application working, webpack was complaining about not being able to find the "vue" module, but I did do manual testing on my personal project and both the new `useReCaptcha` and old usage were working.

### CODE REVIEW

**Comment by WipeAir** [comment]
Hey, sorry for the delay! I haven't had any time yet to look into this topic. 
I'll check your PR in the coming days and fix the things you've mentioned.

**Comment by aklinker1** [comment]
No worries, I understand completely! Most major plugins don't work with vue3 yet either.

**Comment by aklinker1** [comment]
I'll get the conflicts sorted out sometime soon.

**Comment by WipeAir** [comment]
Thanks for the PR! Just merged it into the master (and fixed some minor problems).
The demo application is working fine again and the code style matches the original ESLint configuration. :)

**Pull request merged**
